# Насколько замедлять ломание дерева
# 1.0 = без изменений
# 2.0 = в 2 раза медленнее
# 3.0 = в 3 раза медленнее
#
# Рекомендуется:
# 1.8 - 2.5
slow_multiplier: 2.0

# Включить ли замедление только для брёвен
only_logs: true

# Debug
verbose: false
